### ISSUE TITLE
Error in Authorize Facebook account on Localhost

### ISSUE THREAD

**Issue by bgadiel** [abjerner/Skybrud.Social#37]
Hi,
I installed the plugin on Umbraco7.2.8 and I run into the following error when trying to Authorize my account:
Invalid Scopes: read_stream. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

For Redirect URI I used: www.mylocalsite.com/App_Plugins/Skybrud.Social/Dialogs/FacebookOAuth.aspx
Both in Umbraco backoffice and on FB developer site.

Help is needed,
Thanks.

**Comment by abjerner** [comment]
@bgadiel It seems that Facebook has removed this scope from the most recent version of their API (which is `v2.4` - [read more](https://developers.facebook.com/docs/facebook-login/permissions/v2.4#reference-read_stream)). If you go to your app on the Facebook developer site, can you confirm that your app is using `v2.4`? You should be able to see this at the top of the `https://developers.facebook.com/apps/{appId}/dashboard/` page.

When you register a new app on the Facebook developer site, it will automatically be configured to use the most recent version at the time. So if you just recently registered an app, this will most likely use `v2.4` where this scope has been removed, whereas apps registered at an earlier date might be configured to use an older version. As far as I can see, there is no way of setting your app to use an older version of the API (at least not during login, where this is a problem).

I'm currently working on releasing a new version of Skybrud.Social, and when released, I'll look into fixing this for the Umbraco package. My plan is to create a prevalue editor to select the scopes rather than them being hardcoded as now.

I don't really have a time frame for when I'll have a fix for this, so if you're willing to play around with the source code, you can change the scopes here: https://github.com/abjerner/Skybrud.Social.Umbraco/blob/master/src/Skybrud.Social.Umbraco/App_Plugins/Skybrud.Social/Dialogs/FacebookOAuth.aspx.cs#L109

**Comment by bgadiel** [comment]
Yes, you're correct, my app is registered for v2.4.
I will try to play around and see if I can find a workaround.
Thanks for the quick response.
