### ISSUE TITLE
Facebook API

### ISSUE THREAD

**Issue by JiaweiTan** [abjerner/Skybrud.Social#42]
Hi Abjerner,

For the past few days, I have been learning how to use your library for Twitter, Instagram and Facebook. I'm really glad that this library have helped me out by making the data retrieval so much easier on asp.net. So far, Twitter and Instagram have no problems, except for Facebook.

I used the reference from the Object-oriented communication codes as shown on the image and I entered the access token and user id. However, i can't seem to retrieve any data out and there isn't any errors shown. So, I'm curious whether if the samples codes provided below is sufficient or is there more codes that I have to add on in order to retrieve the data.

Thanks!

![image](https://cloud.githubusercontent.com/assets/9087770/10303005/351dc786-6c43-11e5-940d-5037ac9b36f7.png)

**Comment by abjerner** [comment]
Hi,

I'm glad to hear that the library has helped you ;)

If you're using `v2.4` of the Facebook Graph API (which you're probably are, since it is the newest version), you need to explicitly which fields that should be returned by the Graph API. `v2.4` will only return the `id` and `name` fields/properties will be returned by default.

You can read more about that here: http://social.skybrud.dk/facebook/fields/

**Comment by JiaweiTan** [comment]
Yeah, indeed the problem is that I didn't explicitly specific the fields. Thanks for the speedy replied! :+1:
