### ISSUE TITLE
Posts.GetPosts skipped the video share post?

### ISSUE THREAD

**Issue by peng-at-gruden** [abjerner/Skybrud.Social#58]
Hi,

First of all, thank you so much for providing such a convenient library for the multiple social feed.

I found an issue with using the Facebook API.

```c#
var options = new FacebookGetPostsOptions
{
        Identifier = "156010724437043",
        Fields = "full_picture,name,permalink_url,description,created_time",
        Limit = 8,
};

var response = service.Posts.GetPosts(options);
```

This facebook page (https://www.facebook.com/SydneyOlympicParkArcheryCentre/) has one shared video, however, it's not in the response. Do we skip the video in the result?

The version im using is 0.9.4.4
Thanks

**Comment by abjerner** [comment]
@peng-at-gruden Thanks for the feedback.

Is it this video that you're missing?

https://www.facebook.com/SydneyOlympicParkArcheryCentre/posts/1136663456371760

I think this is more an issue with the API than with Skybrud.Social. Facebook has a tool called Graph Explorer, which is very useful for debugging their API. Your code example above would equal to this:

https://developers.facebook.com/tools/explorer/145634995501895/?method=GET&path=156010724437043%2Fposts%3Ffields%3Dfull_picture%2Cname%2Cpermalink_url%2Cdescription%2Ccreated_time&version=v2.8

As you can see from the response, it doesn't include that particular video. I'm not really sure why, but perhaps it's because it is a shared post.

**Comment by peng-at-gruden** [comment]
@abjerner , Thanks for your reply.

One more issue, the Graph Explorer request you posted upon does return one shared video post (https://www.facebook.com/SydneyOlympicParkArcheryCentre/posts/1127472973957475), however it's not in the response of the .GetPosts() API.

im wondering the "shared post  with video" might not return from the Graph API, however, the "shared video" does. But it's not returned from the library?

**Comment by abjerner** [comment]
@peng-at-gruden I can't see the post that you're linking to. Perhaps it's not public?

What kind of access token do you use with Skybrud.Social? There are three kinds: app, user and page.

By default, the Graph Explorer will generate a user access token for you bound to your Facebook user. A post may be restricted to certain users, groups or simply registered Facebook users in general (meaning you have to login to see the post). If this is the case, you won't be able to retrieve the post using an app access token. Even if you're using a user access token, it might not have the necessary scope to see the post.

For testing, you can try to copy the access token generated by the Graph Explorer and use it in your app. Or the other way around - try posting the access token from your app in the Graph Explorer.

**Comment by peng-at-gruden** [comment]
@abjerner , Thanks a lot for your explanation. 

I was using an app token. So, it's just a content viewing permission issue, not something wrong with the library. :)

Thanks again for your time.

**Comment by biapar** [comment]
How to retrieve the token access page?

**Comment by abjerner** [comment]
@biapar https://social.skybrud.dk/facebook/endpoints/accounts/getting-the-accounts-of-a-user/ or just https://developers.facebook.com/tools/explorer/?method=GET&path=me%2Faccounts&version=v3.2 😉

**Comment by biapar** [comment]
I wish by Skybrud library. The token retrieved by Facebook api explorer has time limit and I need a method to refresh it.
