### ISSUE TITLE
Value was either too large or too small for an Int32. - Instagram issue

### ISSUE THREAD

**Issue by AndersBrohus** [abjerner/Skybrud.Social#59]
Hi @abjerner :-)

Recently i have gotten this error,

Value was either too large or too small for an Int32.

This is the following function i use to contact Instagram,

```
public InstagramRecentMediaResponse getIG(int instaId, int limit)
        {
            var umbracoHelper = new Umbraco.Web.UmbracoHelper(Umbraco.Web.UmbracoContext.Current);
            InstagramOAuthData oAuth = umbracoHelper.Content(instaId).GetPropertyValue("instagramOAuth") as InstagramOAuthData;
            InstagramRecentMediaResponse response = null;

            if (oAuth != null && oAuth.IsValid)
            {
                // Gets an instance of FacebookService based on the OAuth data
                InstagramService service = oAuth.GetService();

                // Gets the most recent posts of the authenticated user (me)
                response = service.Users.GetRecentMedia(new InstagramUserRecentMediaOptions
                {
                    Count = limit
                });
            }
            return response;
        }
```

I can't see what's wrong, it uses 0.9.4.3 version of Skybrud.Social :-)

**Comment by abjerner** [comment]
Hi Anders and thanks for reporting,

I will have a look at this ;)

Something similar has been wrong in the past for locations ([see release notes for 0.9.4.2](https://github.com/abjerner/Skybrud.Social/releases/tag/v0.9.4.2)), so I probably need to change some other properties from `Int32` to `Int64` as well.

Anyways, do you by any chance have a stack trace that for the exception?

**Comment by AndersBrohus** [comment]
![anders](https://cloud.githubusercontent.com/assets/9005889/20142101/b0db916a-a693-11e6-9bb5-0623e719617f.JPG)

I just took a screenshot of the whole screen.. :-)

**Comment by abjerner** [comment]
@AndersBrohus This actually happens for a location, so can you confirm again that you are in fact using `v0.9.4.3` (just asking to be sure)? You can also try to upgrade the newest version AKA `v0.9.4.5`.

**Comment by abjerner** [comment]
Could you try add this line of code just before the line of code that fails (before line 67 based on the screenshot):

```C#
throw new Exception(Skybrud.Social.SocialUtils.GetVersion() + "\n" + Skybrud.Social.SocialUtils.GetFileVersion());
```

It will throw an exception with the version of Skybrud.Social. The reason that I'm asking about the version again is that based on the stack trace, the `JsonObject.GetInt32` method mentioned in the stack trace is called from the `InstagramLocation.Parse` method, but looking at the source code, it really should call `JsonObject.GetInt64`. In other words - it should already be fixed, so I'm a bit confused as to why you're then still seeing this error.

Also, if you have multiple projects in your solution, you should make sure Skybrud.Social is updated in them all (or at least the main project). If two projects reference different versions of the same assembly, it's not always that Visual Studio will get it right.

https://github.com/abjerner/Skybrud.Social/blob/v0.9.x/src/Skybrud.Social/Instagram/Objects/InstagramLocation.cs#L68

![image](https://cloud.githubusercontent.com/assets/3634580/20146019/8ba5b1be-a6a2-11e6-8286-3069d22e7e5a.png)

It could of course also just be because I overlooked something else. In that case, can you send me an example of the JSON that fails? Either just post it here in the comments or send me an email at `abjerner AT skybrud.dk` if it contains something sensitive. That would allow me to test against the exact JSON that are causing you this error ;)

To get the raw JSON, you can trigger a new exception with the JSON as the message like this (again just add it before line 67):

```C#
throw new Exception(service.Users.Raw.GetRecentMedia("me", new InstagramUserRecentMediaOptions {
    Count = limit
}).Body);
```

Hope that helps ;)

**Comment by AndersBrohus** [comment]
We'll try tomorrow @abjerner :)

**Comment by Vassard** [comment]
When we use the 

`throw new Exception(Skybrud.Social.SocialUtils.GetVersion() + "\n" + Skybrud.Social.SocialUtils.GetFileVersion());`

We'll get 0.9.4.1 but it doesn't make any sense, since we just removed Skybrud.Social and Skybrud.Social for Umbraco 7 via NuGet..

Hmmm...

@abjerner

**Comment by AndersBrohus** [comment]
Okay @abjerner we have found a fix! :)

The project keeped referering to 0.9.4.1, even through that 0.9.4.5 was in the bin folder which was installed via NuGet..

So we removed it all via NuGet and downloaded the dll's from Github and then added that to project, and now it works! :)

So we'll just close it now .. :)
