### ISSUE TITLE
Support multiple tags for GetRecentMedia

### ISSUE THREAD

**Issue by bjarnef** [abjerner/Skybrud.Social#66]
At the moment you can get recent media from Instagram with a specific tag using:

```
InstagramRecentMediaResponse response = instagram.Tags.GetRecentMedia("umbraco", instagramOptions.Count);
```

However it doesn't allow you to specify multiple tags, e.g.
```
InstagramRecentMediaResponse response = instagram.Tags.GetRecentMedia("umbraco, cg16", instagramOptions.Count);
```

It would be great if the method has an overload, where first parameter is a string array.
```
InstagramRecentMediaResponse response = instagram.Tags.GetRecentMedia(new string[] { "umbraco", "cg16" }, instagramOptions.Count);
```

For now I can get recent media from multiple tags this way, but is not ideal for e.g. 20 tags.

```
List<ISocialTimelineEntry> entries = new List<ISocialTimelineEntry>();
InstagramRecentMediaResponse response1 = instagram.Tags.GetRecentMedia("umbraco", instagramOptions.Count);
InstagramRecentMediaResponse response2 = instagram.Tags.GetRecentMedia("cg16", instagramOptions.Count);

entries.AddRange(response1.Body.Data);
entries.AddRange(response2.Body.Data);
```

**Comment by abjerner** [comment]
As mentioned in our talk today on Twitter, each method is thought to represent a corresponding method/endpoint in the underlying API. So a method therefore also represents a single request to said API.

The Instagram API doesn't support a single request for multiple hashtags, so like your last code snippet, I would also have to make separate requests to the API for each hashtag. So rather than implementing this in Skybrud.Social, I think it should be up to the individual developer to do so - but of course my documentation can be updated with examples for this.

Hope that makes sense ;)

**Comment by bjarnef** [comment]
@abjerner yes, I submitted the issue before our talk and didn't thought about Instagram only support getting media from a single tag via the API :)

I don't need it right now, but thought it might be useful in some cases, e.g. `#codegarden` and `#cg16`. I have seen other asking for this around the web, so maybe Instagram will add it sometime in the future :ok_hand:
