### ISSUE TITLE
Get Twitter Image From Post

### ISSUE THREAD

**Issue by realtaken** [abjerner/Skybrud.Social#78]
Hey,

Are you able to point me in the right place in getting a photo of a tweet? I see the text property in the Body object but this only includes a link of the image, I need a .jpg so I can display this on my website.

Also Facebook the Picture property only renders to around 100px wide, is this the best thing available at the moment?

Instagram was easy, I have done that :) thank you.

Tom

**Comment by realtaken** [comment]
Hi,

The Media tag is empty which I think is where the image url should be. Is this a bug? Twitter fixed this bug in January 2015.

Tom

**Comment by abjerner** [comment]
@realtaken Things like links, hashtags, users and media in a tweet are exposed through the `Entities` property. As such you can get the first media (if any) through the `tweet.Entities.Media` property:

```C#
@using Skybrud.Social.Twitter.Entities
@using Skybrud.Social.Twitter.Objects
@using Skybrud.Social.Twitter.Responses
@inherits WebViewPage<Skybrud.Social.Twitter.TwitterService>

@{

    TwitterStatusMessageResponse response = Model.Statuses.GetStatusMessage(930827848423825408);

    TwitterStatusMessage tweet = response.Body;

    foreach (TwitterMediaEntity media in tweet.Entities.Media) {

        <pre>@media.MediaUrl</pre>
        <pre>@media.MediaUrlHttps</pre>
        <pre>@media.Url</pre>
        <pre>@media.DisplayUrl</pre>
        <pre>@media.ExpandedUrl</pre>

    }

}
```

Even though `tweet.Entities.Media` is an array, it only exposes the first media in the tweet.

Some tweets have more than one image/media. To get all media from the scenarios, the API also returns a `extended_entities` property in the JSON. **Skybrud.Social** doesn't support this property, but the newer-but-still-in-beta [**Skybrud.Social.Twitter**](https://github.com/abjerner/Skybrud.Social.Twitter) does:

```C#
@using Skybrud.Social.Twitter.Entities
@using Skybrud.Social.Twitter.Objects
@using Skybrud.Social.Twitter.Responses
@inherits WebViewPage<Skybrud.Social.Twitter.TwitterService>

@{

    TwitterStatusMessageResponse response = Model.Statuses.GetStatusMessage(930827848423825408);

    TwitterStatusMessage tweet = response.Body;

    foreach (TwitterMediaEntity media in tweet.ExtendedEntities.Media) {

        <pre>@media.MediaUrl</pre>
        <pre>@media.MediaUrlHttps</pre>
        <pre>@media.Url</pre>
        <pre>@media.DisplayUrl</pre>
        <pre>@media.ExpandedUrl</pre>

    }

}
```

Facebook is slightly more advanced, as there are a number of different issues. If a given post is of the type **photo**, it will also contain the ID of that photo, which you can use to look up further information. It could look something like this:

```C#
@using Skybrud.Social.Facebook.Objects
@using Skybrud.Social.Facebook.Objects.Posts
@using Skybrud.Social.Facebook.Options.Photos
@using Skybrud.Social.Facebook.Options.Posts
@using Skybrud.Social.Facebook.Responses.Photos
@using Skybrud.Social.Facebook.Responses.Posts
@inherits WebViewPage<Skybrud.Social.Facebook.FacebookService>

@{

    FacebookPostsResponse response1 = Model.Posts.GetPosts(new FacebookGetPostsOptions("skybrud") {
        Fields = "id,type,message,created_time,object_id"
    });

    foreach (FacebookPost post in response1.Body.Data) {

        if (post.Type == "photo") {

            FacebookPhotoResponse response2 = Model.Photos.GetPhoto(new FacebookGetPhotoOptions(post.ObjectId) {
                Fields = "images"
            });

            foreach (FacebookImage image in response2.Body.Images) {

                <pre>@image.Source (@(image.Width)x@(image.Height))</pre>
                
            }

        }

    }

}
```

Notice that specifying the right fields is important - otherwise the properties won't be included in the JSON. In the example above, the `Images` property exposes URLs for the photo in various sizes.

Also, as I wrote before, there are a few scenarios you might need to handle - eg. external photos, videos and similar. If necessary, let me know, and I'll try to dig up some more examples ;)

**Comment by realtaken** [comment]
Just turned off my laptop. Thank you so much. That has answered so many of my questions. Look forward to nailing it tomorrow evening :) 

Kind Regards
Thomas McDonough

**Comment by realtaken** [comment]
![twitternomedia](https://user-images.githubusercontent.com/25364614/32978927-85861ae0-cc43-11e7-9e98-c01f62a9c5a9.JPG)

I have done as you said with Twitter and can you see there is no media url but you can clearly see the tweet url and there is a picture on the tweet.

**Comment by realtaken** [comment]
Facebook code worked :) Thank you

**Comment by abjerner** [comment]
@realtaken The Twitter API can be a little weird. The media might now be included in `entities` if it mentioned beyond the first 140 characters of a tweet.

In order to get all media (or entities) of a tweet, the Twitter API allows you to specify a tweet mode for your requests. Default is `compatibility`, but can specify `extended` instead.

As this is a newer feature in the Twitter API (and not that good documented in the Twitter API documentation), is not supported by `Skybrud.Social`.

The latest beta release of [**Skybrud.Social.Twitter**](https://github.com/abjerner/Skybrud.Social.Twitter)  doesn't support this either, but if you pull down the latest code from the GitHub repository, it does. 

With the latest code, you should be able to do something like:

```C#
@using Skybrud.Social.Twitter.Entities
@using Skybrud.Social.Twitter.Enums
@using Skybrud.Social.Twitter.Objects
@using Skybrud.Social.Twitter.Options.StatusMessages
@using Skybrud.Social.Twitter.Responses
@inherits WebViewPage<Skybrud.Social.Twitter.TwitterService>

@{

    TwitterStatusMessageResponse response = Model.Statuses.GetStatusMessage(new TwitterGetStatusMessageOptions(930882535554519040) {
        TweetMode = TwitterTweetMode.Extended
    });

    TwitterStatusMessage tweet = response.Body;

    foreach (TwitterMediaEntity media in tweet.ExtendedEntities.Media) {

        <pre>@media.MediaUrl</pre>
        <pre>@media.MediaUrlHttps</pre>
        <pre>@media.Url</pre>
        <pre>@media.DisplayUrl</pre>
        <pre>@media.ExpandedUrl</pre>

    }
    
    <hr />
    
    <pre>@tweet.JObject</pre>

}
```

I hope that helps for now ;)
