### ISSUE TITLE
Do it work in Xamarin Forms .NET Standard 2.0?

### ISSUE THREAD

**Issue by biapar** [abjerner/Skybrud.Social#83]
Do it work in Xamarin Forms .NET Standard 2.0?

**Comment by abjerner** [comment]
I don't really know for sure. I haven't used Xamarin before, so I wouldn't know how to test against Xamarin specifically.

If we're talking NuGet packages, **Skybrud.Social** is build against the "old" .NET Framework, so I'm almost certain that it won't work in Xamarin.

But the individual packages like [**Skybrud.Social.Facebook**](https://github.com/abjerner/Skybrud.Social.Facebook), [**Skybrud.Social.Twitter**](https://github.com/abjerner/Skybrud.Social.Twitter) and so on are build against multiple frameworks, including .NET Standard 1.3. So I think these should work with Xamarin - but again, I don't know for sure.

**Comment by biapar** [comment]
I'll try but Skybrud.Social is a prerequisite for Skybrud.Social.Facebook. Right? If yes...maybe a problem.

**Comment by abjerner** [comment]
In terms of NuGet packages, `Skybrud.Social.Facebook` depends on `Skybrud.Social.Core`, but not `Skybrud.Social`.

I know it can a bit confusing with the dependencies. I started `Skybrud.Social` back in 2012, and thought it would be best to have all the code in the same package/DLL. Over time I've released that perhaps wasn't the best approach, which is why here now is a separate package for each supported service.
