### ISSUE TITLE
Feature request: generic OAuth support

### ISSUE THREAD

**Issue by jamiehowarth0** [abjerner/Skybrud.Social#91]
I'm going to fork and start a lib that'll add generic OAuth support because I have an unusual requirement to connect to general OAuth2 endpoints. Also, are there any plans to upgrade to support Umbraco 8?

**Comment by abjerner** [comment]
Hi @jamiehowarth0,

Sounds interesting 😉

Keep in mind that this repo is no longer maintained, as the project has spawned into individual repos/packages instead - eg. [Skybrud.Social.Facebook](https://github.com/abjerner/Skybrud.Social.Facebook) and [Skybrud.Social.Google](https://github.com/abjerner/Skybrud.Social.Google) (both using OAuth 2).

The individual packages have a dependency for our [Skybrud.Essentials.Http](https://github.com/skybrud/Skybrud.Essentials.Http) package, which helps with a lot of the HTTP logic. The package does have build-in functionality to work with OAuth 1.0a, but not OAuth 2 specifically.

The different OAuth 2 providers have (or at least have had) slightly different implementations of OAuth 2, which is why the `Skybrud.Essentials.Http` package doesn't have build-in support for support OAuth 2. But things have changed over time. Facebook, for instance, changed parts of their implementation a few years ago. It could be interesting to have another look at whether the package could provider a common implementation (or at least a base) for OAuth 2.

The Umbraco package (which is also a [separate repository](https://github.com/abjerner/Skybrud.Social.Umbraco)) has an alpha release for Umbraco 8, but I haven't really worked on it for more than a year. My plan was to update it to support the same services/providers as the Umbraco 7 package, but I've never been more busy, so unfortunately this package hasn't been prioritized as a result. I hope to change that at some point, but it will probably not be this year.
