### ISSUE TITLE
Getting error When calling GetSelf() method

### ISSUE THREAD

**Issue by vaibhav-shah1988** [abjerner/Skybrud.Social#93]
Hi,
I am trying to use this Wrapper for getting my instagram user info.

I Initiated Service like this 
InstagramService service = InstagramService.CreateFromAccessToken("my accesstoken");

& Then Called this 

var response = service.Users.GetSelf();

I am getting error as "System.ArgumentException: Invalid JSON primitive:"

**Comment by abjerner** [comment]
Hi @vaibhav-shah1988

Skybrud.Social is no longer in active development, and hasn't been for years. This is also mentioned in the README, but I've added an alert at the top to make it more clear. The implementation for each service is now available via individual packages instead.

The reason that your code fails is because Instagram closed down the **Instagram Platform API**, which was what Skybrud.Social used. IIRC this was back in 2019 or something like that.

You should instead use either the **Instagram Basic Display API**  or the **Instagram Graph API**. Both are supported by our newer [**Skybrud.Social.Instagram** package](https://github.com/abjerner/Skybrud.Social.Instagram).

**Comment by vaibhav-shah1988** [comment]
Oh I created issue in wrong repository.
I am using [Skybrud.Social.Instagram](https://github.com/abjerner/Skybrud.Social.Instagram)
Getting same error there.
I have raised issue in that repository.
